version: '3'

services:
  mongodb:
    image: mongo:4.4.9
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mission5w1
    volumes:
      - mongodb-data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/mission5w1

volumes:
  mongodb-data:
